// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Guide",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Guide",
            targets: ["GuideApp"],
            bundleIdentifier: "com.guide.crisisapp",
            teamIdentifier: "96Z2UYRQ77",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "This app requires your location to send SOS distress signals to emergency contacts."),
                .microphone(purposeString: "This app requires microphone access to record voice notes during emergencies.")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/supabase/supabase-swift.git", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "GuideApp",
            dependencies: [
                .product(name: "Supabase", package: "supabase-swift")
            ],
            path: "Sources/Guide"
        )
    ]
)